#' Compute a Z-like score to estimate quality of DMRs
#'
#' @param tumor_table A matrix of beta-values
#' @param control_table A matrix of beta-values
#' @param dmr_table A data.frame generated by [whole_genome_segmentator]
#' @param reference_table A data.frame reporting the genomic coordinates of each CpG site
#' @param out_folder Where to store the data generated. Default to NULL won't save any data
#'
#' @export
calc_sample_score <- function(tumor_table, control_table, dmr_table, reference_table,
                              out_folder = NULL) {
  tumor_table <- as.matrix(tumor_table)
  control_table <- as.matrix(control_table)
  beta_table <- as.matrix(cbind(tumor_table, control_table))
  if (nrow(tumor_table) != nrow(reference_table) || nrow(control_table) != nrow(reference_table)){
    stop("tumor_table and control_table must have same number of rows as reference_table")
  }
  tumor_is_fraction <- all(tumor_table >= 0, na.rm = T) && all(tumor_table <= 1, na.rm = T)
  control_is_fraction <- all(control_table >= 0, na.rm = T) && all(control_table <= 1, na.rm = T)
  if (tumor_is_fraction && control_is_fraction) {
    tumor_table <- tumor_table*100
    control_table <- control_table*100
    storage.mode(control_table) <- "integer"
    storage.mode(tumor_table) <- "integer"
  } else {
    stop("tumor_table and control_table must contain decimal values")
  }
  stopifnot(is.data.frame(dmr_table))
  stopifnot(c('chr', 'start', 'end', 'nseg', 'state', 'avg_beta_diff', 'pval', 'FDR') %in% names(dmr_table))

  sample_state <- c(rep(T, ncol(tumor_table)), rep(F, ncol(control_table)))
  dmr_table <- dmr_table[!dmr_table$state %in% c(NA, 2), ]
  tumor_dmr_beta   <- matrix(nrow = nrow(dmr_table), ncol = ncol(tumor_table))
  control_dmr_beta <- matrix(nrow = nrow(dmr_table), ncol = ncol(control_table))
  z_scores         <- matrix(nrow = nrow(dmr_table), ncol = ncol(tumor_table))

  for (i in seq_len(nrow(dmr_table))) {
    idx_dmr <- with(dmr_table, with(reference_table,
      which(Chromosome == chr[i] & Genomic_Coordinate == start[i]):
        which(Chromosome == chr[i] & Genomic_Coordinate == end[i])))

    tumor_dmr_beta[i, ]  <- apply(beta_table[idx_dmr, sample_state], 2, median, na.rm = T)
    control_dmr_beta[i, ] <- apply(beta_table[idx_dmr, !sample_state], 2, median, na.rm = T)
    z_scores[i, ] <- z_score(tumor_dmr_beta[i, ], control_dmr_beta[i, ])
  }
  rnames <- with(dmr_table, sprintf("chr%s:%s-%s", chr, start, end))
  dimnames(z_scores)    <- list(rnames, colnames(beta_table)[sample_state])
  dimnames(tumor_dmr_beta)  <- list(rnames, colnames(beta_table)[sample_state])
  dimnames(control_dmr_beta) <- list(rnames, colnames(beta_table)[!sample_state])

  if (!is.null(out_folder)) {
    dir.create(out_folder)
    save(tumor_dmr_beta, control_dmr_beta, file = file.path(out_folder, "dmr_beta_table.rda"))
  }
  return(list(z_scores=z_scores, tumor_dmr_beta=tumor_dmr_beta, control_dmr_beta=control_dmr_beta))
}

#' Z-score
#'
#' @param x A numeric vector
#' @param y A numeric vector
#' @keywords internal
z_score <- function(x, y){
  (x - median(y, na.rm = T)) / mad(y, na.rm = T)
}
