#' Find Differentially Methylated Regions across whole genome
#'
#' A function to define DMR for an entire genome.
#'
#' @param tumor_table A matrix of beta-values (percentage) from tumor samples.
#' @param control_table A matrix of beta-values (percentage) from
#' normal/control samples.
#' @param auc_vector A numeric vector generated by [compute_AUC].
#' @param reference_table A data.frame reporting the location of CpG sites
#' (chromosome and genomic_position).
#' @param min_siites Maximum distance between sites within same DMRs.
#' Splits long DMRs.
#' @param min_size An integer to remove streches of differential
#' methylation shorter than cutoff.
#' @param pt_start Transition probability of the HSLM. Default is 0.05.
#' @param normdist Distance normalization parameter of the HSLM. Default is 1e5.
#' @param ratiosd Fraction between the standard deviation of AUC values of
#' differentially methylated sites and the total standard deviation of AUC
#' values. Default is 0.4.
#' @param mu Expected mean (AUC) for hypo-methylated state (1-mu is the
#' expected mean for hyper-methylated state). Default is 0.25.
#' @param use_trunc Use truncated normal distribution (DEBUGGING ONLY).
#' Default is TRUE.
#' @return A data.frame reporting genomic location, number of CpG sites,
#' methylation state, average beta difference (tumor vs. control), p-value and
#' adjusted (Benjamini-Hochberg) p-value (q-value) of discovered DMRs.
#' @importFrom stats mad median p.adjust sd wilcox.test
#' @export
find_dmrs <- function(tumor_table, control_table, auc_vector,
  reference_table, max_distance = Inf, min_sites = 5, pt_start = 0.05,
  normdist = 1e5, ratiosd = 0.4, mu = .25, use_trunc = TRUE){

  # check parameters
  assertthat::assert_that(ratiosd > 0, ratiosd < 1)
  assertthat::assert_that(normdist > 1)
  assertthat::assert_that(pt_start > 0, pt_start < 1)
  assertthat::assert_that(mu >= 0, mu <= .35)
  assertthat::assert_that(is.logical(use_trunc))

  assertthat::assert_that(is.data.frame(reference_table))
  assertthat::assert_that(ncol(reference_table) >= 2)
  assertthat::assert_that(nrow(tumor_table) == nrow(control_table))
  assertthat::assert_that(nrow(tumor_table) == nrow(reference_table))

  min_sites <- as.integer(min_sites)
  tumor_table <- as.matrix(tumor_table)
  control_table <- as.matrix(control_table)

  diff_range_t <- diff(range(tumor_table, na.rm = TRUE))
  assertthat::assert_that(diff_range_t > 1, diff_range_t <= 100, msg = "For computation efficiency, convert tumor table to percentage values.")
  diff_range_c <- diff(range(control_table, na.rm = TRUE))
  assertthat::assert_that(diff_range_c > 1, diff_range_c <= 100, msg = "For computation efficiency, convert control table to percentage values.")

  tumor_table <- round(tumor_table)
  control_table <- round(control_table)
  storage.mode(tumor_table) <- "integer"
  storage.mode(control_table) <- "integer"

  # remove NA rows
  idx_not_NA <- which(!is.na(auc_vector))
  tumor_table <- tumor_table[idx_not_NA,, drop = FALSE]
  control_table <- control_table[idx_not_NA,, drop = FALSE]
  auc_vector <- auc_vector[idx_not_NA]
  reference_table <- reference_table[idx_not_NA,, drop = FALSE]

  # sort data
  idx <- order(reference_table[[1]], reference_table[[2]])
  reference_table <- reference_table[idx, ]
  tumor_table <- tumor_table[idx, ]
  control_table <- control_table[idx, ]
  auc_vector <- auc_vector[idx]

  tumor_beta_mean <- apply(tumor_table, 1, mean, na.rm = TRUE)
  control_beta_mean <- apply(control_table, 1, mean, na.rm = TRUE)
  mean_beta_diff <- tumor_beta_mean - control_beta_mean
  auc_sd <- sd(auc_vector, na.rm = TRUE)

  chromosomes <- as.character(unique(reference_table[[1]]))
  all_dmrs <- vector("list", length(chromosomes))
  n <- 1
  for (n in seq_along(chromosomes)) {
    chr <- chromosomes[n]
    idx_chr <- which(reference_table[[1]] == chr)
    message(paste("Processing chromosome", chr))

    t_beta_mean_subset <- tumor_beta_mean[idx_chr]
    c_beta_mean_subset <- control_beta_mean[idx_chr]
    mean_beta_diff_subset <- mean_beta_diff[idx_chr]
    auc_subset <- auc_vector[idx_chr]
    coordinates <- reference_table[[2]][idx_chr]

    # 1) compute methylation states (1,2,3)
    meth_states <- meth_state_finder(auc_subset, coordinates, auc_sd, pt_start,
                                     normdist, ratiosd, mu, use_trunc)

    # 2) find segments
    dmrs <- segmentator(t_beta_mean_subset,
                        c_beta_mean_subset,
                        meth_states,
                        coordinates,
                        max_distance,
                        min_sites)

    all_dmrs[[n]] <- tibble::add_column(dmrs, chr=chr, .before="start")
  }
  all_dmrs <- dplyr::bind_rows(all_dmrs)
  all_dmrs$q_value <- p.adjust(all_dmrs$p_value, "fdr")
  return(all_dmrs)
}

