#' Generate files from a set of DMR
#'
#' For a quick visualization using a genome browser like IGV, this function
#' generates [BED](https://bit.ly/1hdVNjA) and [SEG](https://bit.ly/2J2WZdZ)
#' files of statistically significant hyper-methylated and hypo-methylated
#' DMRs.
#'
#' BED files (hyper- and hypo-methylated DMRs separately) report genomic
#' location and q-value (in form of -log10(q)).
#' SEG files report average beta differences between tumor and normal/control
#' samples at each DMR.
#' Additionally, a SEG file reporting Z-scores for each tumor sample is
#' generated providing a list produced by [compute_z_scores].
#'
#' NOTE: BED files have 0-based coordinates while SEG files have 1-based
#' coordinates.
#'
#' @param path A string including absolute or relative path: "_hyper.bed" and
#' "_hypo.bed" are automatically added.
#' @param dmr_table A data.frame generated by [find_dmrs].
#' @param z_score_table A list generated by [compute_z_scores].
#' @param qvalue_thr A numerical threshold. Report only DMRs with a q-value
#' lower than threshold.
#' @return Nothing. Only saves output tables.
#'
#' @importFrom utils write.table
#' @importFrom dplyr %>%
#' @export
write_output <- function(path, dmr_table, z_score_table = NULL, qvalue_thr = 0.05){
    # check parameters
    if (missing(path)) {
        stop("Provide a path to write BED and/or SEG files.")
    }
    assertthat::assert_that(is.data.frame(dmr_table))
    if (!is.null(z_score_table)){
        assertthat::assert_that(is.list(z_score_table))
    }
    qvalue_thr <- as.numeric(qvalue_thr)
    assertthat::assert_that(!is.na(qvalue_thr))
    assertthat::assert_that(qvalue_thr > 0, qvalue_thr <= 1)

    idx_dmr <- which(dmr_table$q_value < qvalue_thr)
    if (length(idx_dmr) == 0){
        warning("No DMR with significant q-value retrieved, hence no output produced.")
        return(NULL)
    }

    # write bed files
    idx_names <- c("chr", "start", "end", "nsites", "q_value")
    idx_hyper <- which(dmr_table$state[idx_dmr] == 3)
    idx_hypo  <- which(dmr_table$state[idx_dmr] == 1)
    out_table_bed <- dmr_table[idx_dmr, idx_names]
    out_table_bed$start <- out_table_bed$start - 1
    out_table_bed$end <- out_table_bed$end - 1
    out_table_bed$q_value <- -log10(out_table_bed$q_value)
    write.table(out_table_bed[idx_hyper, ],
                file = paste0(path.expand(path), "_hyper.bed"),
                sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)
    write.table(out_table_bed[idx_hypo, ],
                file = paste0(path.expand(path), "_hypo.bed"),
                sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)

    # write seg files
    idx_names <- c("chr", "start", "end", "nsites", "avg_beta_diff")
    out_table_seg <- dmr_table[idx_dmr, idx_names]
    out_table_seg <- data.frame(ID = basename(path), out_table_seg)
    write.table(out_table_seg, paste0(path.expand(path), ".seg"), sep = "\t",
                quote = FALSE, row.names = FALSE)

    if (!is.null(z_score_table)){
        idx_names <- c("chr", "start", "end", "nsites")
        out_table_sample <-
            cbind(dmr_table[idx_dmr, idx_names], z_score_table$z_scores[idx_dmr,]) %>%
            tidyr::gather(ID, z_score, -c(chr:nsites)) %>%
            dplyr::select(ID, chr:nsites, z_score)
        write.table(out_table_sample, paste0(path.expand(path), "_z_scores.seg"),
                    sep = "\t", quote = FALSE, row.names = FALSE)
    }
}
