#' Generate a bed file from a set of DMR
#'
#' This function generates a bed format file(https://bit.ly/1hdVNjA)
#' for a quick visualization using a genome browser.
#'
#' @param dmr_table A data.frame generated by [whole_genome_segmentator].
#' @param prefix A string including absolute or relative path: "_hyper.bed" and
#' "_hypo.bed" are automatically added.
#' @param qvalue_thr A numerical threshold. Report only DMRs with a q-value
#' lower than threshold.
#' @param zero_based A logical. Whether the output coordinates are 0-based
#' (default) or 1-based.
#'
#' @importFrom utils write.table
#' @export
write_bed <- function(dmr_table, path, qvalue_thr = 0.05, zero_based = TRUE){
  stopifnot(is.data.frame(dmr_table))
  qvalue_thr <- as.double(qvalue_thr)
  zero_based <- as.logical(zero_based)

  if (zero_based){
    dmr_table$start <- dmr_table$start - 1
    dmr_table$end <- dmr_table$end - 1
  }
  idx_hyper <- which(with(dmr_table, state == 3 & q_value < qvalue_thr))
  idx_hypo  <- which(with(dmr_table, state == 1 & q_value < qvalue_thr))

  col_names <- c("chr", "start", "end", "nseg", "avg_beta_diff")
  write.table(dmr_table[idx_hyper, col_names], paste0(path.expand(path), "_hyper.bed"),
      sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)
  write.table(dmr_table[idx_hypo, col_names], paste0(path.expand(path), "_hypo.bed"),
      sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)
}
