#' Generate files from a set of DMR
#'
#' For a quick visualization using a genome browser, this function generates
#' one BED file (https://bit.ly/1hdVNjA) and two SEG files
#' (https://bit.ly/2J2WZdZ) reporting statistically significant
#' hyper-methylated and hypo-methylated DMRs.
#'
#' BED files coordinates are 0-based while SEG files 1-based.  BED file reports
#' genomic location and q-values as -log10(q) associated to DMRs.  One SEG file
#' reports Z-scores for single samples, the other reports average beta
#' differences (tumor-control) for the entire set of samples (e.g. tumor type).
#'
#' @param dmr_table A data.frame generated by [whole_genome_segmentator].
#' @param sample_score A data.frame generated by [calc_z_score].
#' @param path A string including absolute or relative path: "_hyper.bed" and
#' "_hypo.bed" are automatically added.
#' @param qvalue_thr A numerical threshold. Report only DMRs with a q-value
#' lower than threshold.
#'
#' @importFrom utils write.table
#' @importFrom dplyr `%>%`
#' @export
write_output <- function(dmr_table, sample_score, path, qvalue_thr = 0.05){
  # check parameters
  qvalue_thr <- as.numeric(qvalue_thr)
  assertthat::assert_that(is.data.frame(dmr_table))
  assertthat::assert_that(is.list(sample_score))
  if (missing(path)) {
    stop("Provide a path to write BED and SEG files.")
  }
  dmr_table <- dplyr::filter(dmr_table, state %in% c(1,3))
  idx_dmr <- which(dmr_table$q_value < qvalue_thr)
  if (length(idx_dmr) == 0){
    warning("No DMR with significant q-value retrieved, hence no output produced.")
    return(NULL)
  }

  # write seg files
  idx_names <- c("chr", "start", "end", "nseg", "avg_beta_diff")
  out_table <- dmr_table[idx_dmr, idx_names]
  out_table <- data.frame(ID = basename(path), out_table)
  write.table(out_table, paste0(path.expand(path), ".seg"), sep = "\t",
    quote = FALSE, row.names = FALSE)

  idx_names <- c("chr", "start", "end", "nseg")
  out_table_sample <-
    cbind(dmr_table[idx_dmr, idx_names], sample_score$z_scores[idx_dmr,]) %>%
    tidyr::gather(ID, z_score, -c(chr:nseg)) %>%
    dplyr::select(ID, chr:nseg, z_score)
  write.table(out_table_sample, paste0(path.expand(path), "_z_scores.seg"),
    sep = "\t", quote = FALSE, row.names = FALSE)

  # write bed files
  dmr_table$start <- dmr_table$start - 1
  dmr_table$end <- dmr_table$end - 1
  idx_names <- c("chr", "start", "end", "nseg", "q_value")
  out_table <- dmr_table[idx_dmr, idx_names]
  out_table$q_value <- -log10(out_table$q_value)
  write.table(out_table, paste0(path.expand(path), ".bed"), sep = "\t",
    quote = FALSE, row.names = FALSE, col.names = FALSE)
}
