#' Generate a bed file from a set of DMR
#'
#' This function generates a [bed format file](https://bit.ly/1hdVNjA)
#' for a quick visualization using a genome browser.
#'
#' @param dmr_table A data.frame generated by [whole_genome_segmentator].
#' @param path A character vector containing a single path name.
#' @param qvalue_thr A numerical threshold. Report only DMRs with a q-value
#' lower than threshold.
#' @param one_based A logical. Wether the output coordinates are 0-bases or
#' 1-based (default).
#'
#' @importFrom utils write.table
#' @export
write_bed <- function(dmr_table, path, qvalue_thr = 0.05, one_based = TRUE){
  stopifnot(is.data.frame(dmr_table))
  qvalue_thr <- as.double(qvalue_thr)
  zero_based <- as.logical(zero_based)

  row_idx <- which(with(dmr_table, state != 2 & q_value < qvalue_thr))
  out_data <- dmr_table[row_idx, c("chr", "start", "end", "nseg", "avg_beta_diff", "q_value")]
  out_data$q_value <- -log10(q_value)
  if (!one_based){
    out_data$start <- out_data$start - 1
    out_data$end <- out_data$end - 1
  }
  write.table(out_data, file = path.expand(path), sep = "\t", quote = FALSE,
    row.names = FALSE, col.names = FALSE)
}
